# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='name',
        ),
    ]
