# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
