# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_testimonial_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
